### ISSUE TITLE
BillingActivity Not finished after purchase.

### ISSUE THREAD

**Issue by khatchik** [freshplanet/ANE-In-App-Purchase#11]
Hi, 

My name is Carlos.

I downloaded this ANE (feature/google play v3) and everything looks pretty good.
I could connect, buy and receive all the necessary information.

The only problem that I found , and the only way that I tested this is with test purchases ("android.test.purchased") is that after Google Play sends me the purchase_succesfull and my Flex/AIR project receives the event, that Activity remains and only clicking the back button makes the activity stop.

Other note here is that this started happening to me when the interface of purchases changed in Google Play, before I had a google play page opened and now its like a popup inside the activity

I created a command for each request 
- Inits (with google key)
- add events listeners
- makes purchase
- removes event listeners
- stop

The problem is that the stop does not destroy the activity and I found that in the BillingActivity the finish() is commented after the purchase succesfull.

I also debug this with Flex, and also adb logcat to see the result.

I don't know what else I can do to fix this. The only thing left I think is to add that finish recompile everything and see if it works.

Any help would be apreciated.

P.S: Your code is neat. Thanks for sharing!

**Comment by k2xl** [comment]
Hey, considering there seems to be zero documentation, any chance you could share some code snippets of how you got things to work?

**Comment by tsangwailam** [comment]
I have add the finish() in the OnIabPurchaseFinishedListener and now it will return to app after purchase.
