### ISSUE TITLE
How to "consume" in android purchases?

### ISSUE THREAD

**Issue by quilombodigital** [freshplanet/ANE-In-App-Purchase#14]
Android purchases can "consume" an item in order to buy it again (for example when you buy a specific game potion that can be bought many times)
From what I saw at the code, this is not supported. Is this true?
some references at http://developer.android.com/google/play/billing/api.html

[]s, gandhi

**Comment by arnotvgids** [comment]
If you have the v3 branch, this should be possible using the InAppPurchase.getInstance().removePurchaseFromQueue method. But for me personally this is not working, you have to supply the productId & purchaseToken as far as I understand (and read the code). But I'm not confident I do everything correctly... (note: I also tried productId & the whole receipt as string, but no luck..)

Maybe someone can shine a light on how to achieve this? thanks!

**Comment by clam61** [comment]
bump. do we use the purchaseToken? maybe the orderid?
