### ISSUE TITLE
In-App Billing V3 ?

### ISSUE THREAD

**Issue by juliephiloche** [freshplanet/ANE-In-App-Purchase#16]
Hi, 

I've seen that your ANE target the Android in-app purchase v2.
Are there a solution to the current v3 ?
I'm on a quick project and i've not expected this change.

Thanks to help me !

**Comment by ataugeron** [comment]
Hi,

You can use the branche feature/googleplayv3. I'm working on merging this
branch with the main one, it should be ready soon.

Best
Alex

**Comment by juliephiloche** [comment]
Thanks !
Is it this one ?
https://github.com/alvinlaw/adobe-native-extension-in-app-purchase

How can I get all products info purchase ?
Do I know all packages_ID in the application?

Thanks

**Comment by clam61** [comment]
ataugeron

I checked out the code in googleplayv3. I don't see any method for consuming a product. Could you point me in the right direction?

**Comment by ataugeron** [comment]
removePurchaseFromQueue

**Comment by clam61** [comment]
thanks

so in the non v3 main branch, what does removePurchaseFromQueue do?

Is it necessary to call that after every product purchase?

**Comment by ataugeron** [comment]
v3 will soon be merged in develop. But fyi, in the previous version
removePurchaseFromQueue does nothing on Android, but does remove the
purchase from the queue on iOS. On iOS, you should always call it after a
successful purchase. On Android, it the previous version it doesn't matter,
but in the new version (v3) you should also call it after a successful
purchase.

**Comment by clam61** [comment]
I just created a new thread--I thought removePurchaseFromQueue would solve it.

I am using the main branch and an unmanaged product.

My purchase success event gets triggered multiple times, sometimes minutes after a purchase sometimes immediately.

In the receipt I see multiple orders in the array (orders from the past), but I am only charged once.  

Any idea as to what is going on?
