### ISSUE TITLE
PURCHASE_SUCCESS called multiple times on Android

### ISSUE THREAD

**Issue by clam61** [freshplanet/ANE-In-App-Purchase#17]
Purchasing an unmanaged product works and the PURCHASE_SUCCESS event triggers, but then a few minutes later the PURCHASE_SUCCESS event gets triggered again multiple times.

**Comment by clam61** [comment]
btw, i am using the main branch and am calling 

function removePurchaseFromQueue(productId:String, receipt:String):void

passing in the productId and orderId for android. this is correct?

**Comment by kerike** [comment]
Hi clam61,

I've been seeing the same problem for a couple of days. It happens on ios, and only for one user.
I have an event handler function: 

inAppInstance.addEventListener(InAppPurchaseEvent.PURCHASE_SUCCESSFULL, onReceived);

and in the onReceived I do a php post to our server to give the player his points.
The post is called two times in the same second. So the player is charged only once (based on apple stats) and he gets the points two times.

Did you figure out what is the problem? I tried spamming the buy button but every hit is a different payment and a different SUCCESS event triggered.
