### ISSUE TITLE
getProductsInfo Doesn't work on android platform.

### ISSUE THREAD

**Issue by imyourm8** [freshplanet/ANE-In-App-Purchase#18]
Hi, i downloaded google-v3 branch and tried to purchase consumable in-app. It works ok. But i have another problem. I can't get products from account. 

inapp.init(Constants.GP_KEY, true);

var items:Array = [];
for (var i:int = 0; i < Products.ids.length; ++i) {
    items[i] = Products.ids[i].id;
}
inapp.getProductsInfo(items, []);

This is how i trying to get them. But no luck. After call there are nothing happens. Where i am wrong?

**Comment by nicolechen819** [comment]
I have the same problem, can anyone help?

**Comment by Nestordu** [comment]
me too.......

**Comment by albanD** [comment]
Try this

import com.freshplanet.ane.AirInAppPurchase.InAppPurchaseEvent;
//you should already have this somewhere

inapp.init(Constants.GP_KEY, true);

var items:Array = [];
for (var i:int = 0; i < Products.ids.length; ++i) {
items[i] = Products.ids[i].id;
}

function onInfoReceived(event:InAppPurchaseEvent):void
{
    //remove the event listener
    var yourData:Object = JSON.parse(event.data);
}

//you should also handle the errors with onInfoError(event)

inapp.addEventListener(InAppPurchaseEvent.PRODUCT_INFO_RECEIVED, onInfoReceived);
inapp.addEventListener(InAppPurchaseEvent.PRODUCT_INFO_ERROR, onInfoError);
inapp.getProductsInfo(items, []);

I am not 100% sure but that should do the trick

**Comment by satishgowda28** [comment]
In trace i get this {"details":{},"purchases":[]} pls help. I do pass the item array
