### ISSUE TITLE
How to use "ANE-In-App-Purchase"?

### ISSUE THREAD

**Issue by cte-app-koiso** [freshplanet/ANE-In-App-Purchase#19]
Hi,

How to use "ANE-In-App-Purchase"?
I can't understand how to use "AirInAppPurchase.ane".
Will you tell me how to call it from actionscript source code or
tell me sample actionscript source code?

**Comment by cte-app-koiso** [comment]
I send my programming code.
Is this OK?
(I used "developper-branch".)

btn_buy_s.addEventListener(MouseEvent.CLICK, buy_s);
function buy_s(event:MouseEvent):void
{
    var kakin:InAppPurchase = new InAppPurchase();
    if(kakin.isInAppPurchaseSupported == true){
        txt_kakin.text = "InAppPurchase OK";
    }else{
        txt_kakin.text = "InAppPurchase NG";
    }

```
var _i_kakin:InAppPurchase = InAppPurchase.getInstance();
_i_kakin.init();
var arr_productsInfo:Array = new Array;
arr_productsInfo.push("purupuru_0001");

_i_kakin.getProductsInfo(arr_productsInfo);
_i_kakin.makePurchase("purupuru_0001");
```

}

**Comment by akunerio** [comment]
how use?
