### ISSUE TITLE
IOS version event "PRODUCT_INFO_SUCCESS" should change to "PRODUCT_INFO_RECEIVED"

### ISSUE THREAD

**Issue by tsangwailam** [freshplanet/ANE-In-App-Purchase#21]
In IOS version, it write product received event string to "PRODUCT_INFO_SUCCESS". But, it should be "PRODUCT_INFO_RECEIVED" according to Action Script event.

**Comment by florianbrochard** [comment]
Same issue here. So it's impossible to get price dynamically from Apple.

**Comment by tsangwailam** [comment]
@florianbrochard You can change the iOS version and rebuild. and it will work.

**Comment by kerike** [comment]
Hi guys,

I have the same problem. Has someone rebuilt it, and get it to work? I don't have mac to rebuild the ane. If someone could help me, it would be great.

Thanks.

**Comment by tsangwailam** [comment]
Here is a new build.
https://dl.dropboxusercontent.com/u/163440/AirInAppPurchase.ane

**Comment by florianbrochard** [comment]
Thank you @tsangwailam ! Very nice of you :)

**Comment by umarmustafa** [comment]
Thanks @tsangwailam 
I was just about to rebuild it, found this instead.

**Comment by tsangwailam** [comment]
Just for anybody interesting. Here is the fork which added the restoreTransaction in IOS and fix getProductInfo.
https://github.com/digicrafts/ANE-In-App-Purchase

**Comment by kerike** [comment]
Thank you @tsangwailam!

**Comment by lindagattino** [comment]
i would need to know if the user has already bought a product... how do you think i could do it? I tought it was with product info but I can see just product description and price...
