### ISSUE TITLE
v3 iOS restore transaction

### ISSUE THREAD

**Issue by KosmoGalaxy** [freshplanet/ANE-In-App-Purchase#22]
How do you restore transactions in iOS in v3? I can see that there is a function written for that but it's not implemented as an ANE function.

**Comment by tsangwailam** [comment]
Yes. but not in the proper way (i think). I need to rewrite the part for restore transaction.

**Comment by tsangwailam** [comment]
Just for anybody interesting. Here is the fork which added the restoreTransaction in IOS and fix getProductInfo.
https://github.com/digicrafts/ANE-In-App-Purchase

**Comment by esdebon** [comment]
Here the @tsangwailam fix on the newest version and Androidx86 support

With this you retrieve the items from the appstore:
InAppPurchase.getInstance().restoreTransactions(true);

https://github.com/Fluocode/ANE-In-App-Purchase
