### ISSUE TITLE
No call back is called and no inapp purchase dialog appears

### ISSUE THREAD

**Issue by abdallaramadan** [freshplanet/ANE-In-App-Purchase#26]
Hello,

Thank you very much for this useful ANE. However I have problem running it. I used the latest binary in the develop branch.
I have initialization code like this...

InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PURCHASE_SUCCESSFULL, successFullPayment);
InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PRODUCT_INFO_RECEIVED,onProductReceived);
InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PURCHASE_DISABLED,onDisabled);
InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PURCHASE_ENABLED,onEnabled);
InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PURCHASE_ERROR,onError);
InAppPurchase.getInstance().addEventListener(InAppPurchaseEvent.PRODUCT_INFO_ERROR, onProductError);

InAppPurchase.getInstance().init(omit google play id, true);

The result in the log looks like the following.
[InAppPurchase]  in app purchase is supported 
[InAppPurchase]  in app purchase is supported 
[InAppPurchase] init library
[InAppPurchase]  in app purchase is supported 

Then I make purchase like this...
InAppPurchase.getInstance().makePurchase(inappID);

The log appears like this...
[InAppPurchase]  in app purchase is supported 
[InAppPurchase] purchasing fullstory

Then it stops here without calling any callback and nothing appears related to inapp purchase in my air application.

Thanks for advance.

**Comment by matejgv3** [comment]
for me too

**Comment by VictorOs** [comment]
I had the same thing. When I debugged, I saw that BillingActivity failed to start. Adding 
<activity android:name="com.freshplanet.inapppurchase.BillingActivity"/>
line to <application> section in android manifest addition in descriptor xml file solved the problem.

**Comment by kaifakh22** [comment]
same here.I am implementing on ios.
@abdallaramadan you got any solution?

**Comment by ChrisGamePill** [comment]
can someone please post their whole <android> ... </android> configuration. I can't receive any purchase success no mater what combination of <activity android <service android .... etc I'm trying. Please help and thanks!

**Comment by rankorn** [comment]
Check out this: https://github.com/freshplanet/ANE-In-App-Purchase/issues/30

But I must admit that I moved to another implementation after using this one.

**Comment by ChrisGamePill** [comment]
Yeah I tried the #30, now I even ended up losing some stuff in the application.xml regarding some responding services, billing related. 

Anyway nothing seems to work here, and from the look of Starling related threads online it looks like freshplanet is not really using this or this version of the ANE, the catLog looks a bit different from what I've getting. 

Would you please share what other Android IAP friendly ANE have you found? Please and thanks!
