### ISSUE TITLE
consume a purchase

### ISSUE THREAD

**Issue by shevasn** [freshplanet/ANE-In-App-Purchase#27]
I'm not able to consume a purchase.  I think the problem may be in the parameters I'm sending to the InAppPurchase.getInstance().removePurchaseFromQueue() function.

the purchase exists, and I do have all the actual purchase info received from Google, but how exactly should I arrange the string of the variables id and receipt?

thank you for your help.

**Comment by dreammonkey** [comment]
here's how I do it on Android, on iOS the process is more straightforward...

private function onPurchaseSuccessfull(event:InAppPurchaseEvent):void
{
    trace('onPurchaseSuccesfull', event.data);

```
var purchaseResult:Object

// receiptType : GooglePlay
// receipt: this is the one you need...

purchaseResult = JSON.parse(event.data);
const receipt:Object = purchaseResult['receipt'];
//trace('JSON.stringify(receipt): ' + JSON.stringify(receipt));
//trace(this, 'receipt["signedData"]', receipt["signedData"]);
const signedData:Object = JSON.parse(receipt["signedData"]);
//trace(this, 'signedData["productId"]', signedData["productId"]);

// download the purchase (finish the transaction)
_service.removePurchaseFromQueue(signedData["productId"],JSON.stringify(receipt));
```

}

**Comment by shevasn** [comment]
wow!! it works - finally after so much testing.
thanks a lot

**Comment by ChrisGamePill** [comment]
Can't receive any PURCHASE_SUCCESS from Google Play, the rest looks fine, product list seems OK. Need help with figuring out what to put into the application.xml.
