### ISSUE TITLE
iOS keeps rejecting my app. (But it works!)

### ISSUE THREAD

**Issue by jaimedominguez** [freshplanet/ANE-In-App-Purchase#34]
Apparently ,they say:

We found that while you have submitted In App Purchase products for your app, the In App Purchase functionality is not present in your binary.

If you would like to utilize In App Purchase in your app, you will need to upload a new binary that incorporates the In App Purchase API to enable users to make a purchase.

But the functionality works and the ANE is obviously added.
And AIR version is: 4.0.

 It has been the the third version I have sent them and my patience (after two months) is running out. If an the app works and it has the ANE, what else am I supposed to do here?

Help!

**Comment by rankorn** [comment]
I am using Adobe's ANE for in-app purchase on iOS, it works and it passes Apple's submission process.
Adobe has an ANE that supports only iOS so for Android you will have to use another one.

It's part of Adobe's Gaming SDK and it's free:
http://www.adobe.com/devnet/air/native-extensions-for-air.html

**Comment by esdebon** [comment]
I just approve two applications, with In-App-Purchases. The "ane" that use was this (on iOS and Android):

https://github.com/Fluocode/ANE-In-App-Purchase
