### ISSUE TITLE
Can't make purchases in debug on Android device

### ISSUE THREAD

**Issue by korimako** [freshplanet/ANE-In-App-Purchase#40]
When I publish the app and Export Release version, I can successfully make purchases, but I can't see any debugging in the console. When I debug the same version on the device, I can see the debugging but get an error: "This version of the application is not configured for billing through Google Play." 
I can get product info and restore transactions in this mode, I just can't make a purchase. Is there something that I can change in my Flashbuilder debug configurations that will let me pay in this mode? I took the 'debug' string off the end of the App Id in the debug configurations.

Anything obvious that I might be missing?

**Comment by esdebon** [comment]
You can use the ADT to debugg use with the logcat, with this you can get much more information.

https://developer.android.com/sdk/index.html?hl=i

**Comment by korimako** [comment]
Thanks, yes I use that, but I don't see my AS traces in the release version. I am trying to debug my own code in the case of a successful payment. Is it just not possible, I am fine if it isn't but I was wondering if it is just a configuration mistake on my part!

**Comment by esdebon** [comment]
hehehe, export a debug version to your device and use the logcat

http://help.adobe.com/en_US/Flex/4.0/UsingFlashBuilder/WS6f97d7caa66ef6eb1e63e3d11b6c4d0d21-7f99.html

The release version have a "omit trace statements" parameter... or you can compile the apk using the command line

**Comment by sherifelshazli** [comment]
Did you figure out what your issue was, I'm able to retrive the product info successfully, but makepurchase returns nothing.. even "android.test.purchased".
