### ISSUE TITLE
SKUDetails for Price Currency Code

### ISSUE THREAD

**Issue by JLeine** [freshplanet/ANE-In-App-Purchase#41]
I've checked the code for Android and it turned out that the SKU Details class has no getter for the currency iso code.

Since Google has updated this in the Google Play In-app Billing Reference (V3), http://developer.android.com/google/play/billing/billing_reference.html#getSkuDetails, this should be available as well.

**Comment by JLeine** [comment]
Someone knows something about?

**Comment by esdebon** [comment]
I'm not sure, but I think it was here resolved
https://github.com/Fluocode/ANE-In-App-Purchase
