### ISSUE TITLE
Authentication required on purchases?

### ISSUE THREAD

**Issue by hampusboas** [freshplanet/ANE-In-App-Purchase#42]
Hello,
I'm getting Authentication required when i try to buy something.
I've googled around a bit and i came up to that you cant have the same account in google play store as the owner off the app, so i created a new Gmail and restored the whole phone. but im getting the same result. I am very confused do you guys have the answer?

Best regards Hampus

**Comment by lukebellamy053** [comment]
I am getting this same issue. If anyone could help it would be great!

**Comment by esdebon** [comment]
You need a beta testers group (a google group to get authorization)
http://pugetworks.com/blog/2013/06/beta-testing-android-apps-on-the-google-play-store/

**Comment by smival** [comment]
I made following steps:
1) Upload APK file into Alpha version tab in developer console
2) Make a google group and add it on Alpha version tab and Beta version tab in developer console
3) Make an another google profile for test and joint to group mentioned above
4) On my android device switch current account to test account mentioned above and run a debug version of the application using debugging by cable.

After calling InAppPurchase.getInstance().makePurchase(productId); I see a message about "Authentication required"

did I Something wrong?

**Comment by sherifelshazli** [comment]
Hi smival, did you figure out why you were getting the "Authentication required" ?
