### ISSUE TITLE
New ANE can not be used in android

### ISSUE THREAD

**Issue by laan** [freshplanet/ANE-In-App-Purchase#45]
The new ANE is unavaiable in android. the code as following:

InAppPurchase.getInstance().userCanMakeAPurchase()

It throw new Error: ArgumentError:Error #3500

**Comment by Jacowaco** [comment]
I'm experiencing the same problem:

[InAppPurchase]  in app purchase is supported 
[InAppPurchase] check user can make a purchase
[Fault] exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name userCanMakeAPurchase.

**Comment by Jacowaco** [comment]
In fact i can't do anything in Android, no products are detected in getProductInfo, and when i try to buy Google sends an error alert.

**Comment by Jacowaco** [comment]
The rest of the methods work for me. Only this one gives me an error in Android
