### ISSUE TITLE
in app purchase is not supported

### ISSUE THREAD

**Issue by Anandbabuas3** [freshplanet/ANE-In-App-Purchase#49]
i am trying to add in app purchase features in my iOS app. i have used fresh planet nativeExtension
(AirInAppPurchase.ane).while i compiling, it traces "in app purchase is not supported"... 

Things  i used.
1. Adobe Flash pro CS6(AS3).
2. Adobe AIR SDK 17.
3. Window 7. 

i correctly link nativeExtension(AirInAppPurchase.ane) in my project
i correctly configured my iOS-app for in-app purchase in iTunes connection.
i think  i made mistake in documentation...

Things I want to know
1. Where to put my product id in my project(as3 classs).
2. What is the use of 
Capabilities.manufacturer.indexOf('iOS') > -1 || Capabilities.manufacturer.indexOf('Android') > -1;"
which is in InAppPurchase.as.
3. What is the use of ExtensionContext.createExtensionContext("com.freshplanet.AirInAppPurchase", null);
4. what is the clear documentation for in-app purchase for iOS-app.

please help me.... For this reason i am struggling. i couldn`t go further step..

**Comment by Anandbabuas3** [comment]
i tested in iOS devices, its work.. only thing is that, event PURCHASE_SUCCESSFULL is not work, after     transaction got completed, it didn't give any intimation....Please any one help me....

**Comment by qwpking** [comment]
i tested in iOS devices，PURCHASE_SUCCESSFULL still not work!!!!! -_-||
