### ISSUE TITLE
which ane are you using in SongPop for showing reward videos?

### ISSUE THREAD

**Issue by rubel** [freshplanet/ANE-In-App-Purchase#5]
Thanks for sharing some very helpful anes.
which ane are you using in SongPop for showing reward videos?

**Comment by ataugeron** [comment]
Hi @rubel !

The rewarded videos are a feature of Flurry's AppSpot:

http://flurry.com
https://github.com/freshplanet/ANE-Flurry

**Comment by rubel** [comment]
is it possible to implement the reward video ads with this ane? or you have any other ane for that?

**Comment by ataugeron** [comment]
As I just said, the reward videos are implemented with the Flurry ANE: https://github.com/freshplanet/ANE-Flurry

**Comment by rubel** [comment]
can you please give me a snippet of code or any hint for implementing the reward video with this ane? it will be very very helpful for me.
