### ISSUE TITLE
RestoreTransactions don't work on Android

### ISSUE THREAD

**Issue by Provlax** [freshplanet/ANE-In-App-Purchase#53]
RestoreTransaction method don't work on Android. ADM error: 
In-app billing error: Illegal state for operation (queryInventory): IAB helper is not set up.

 Doesn't it work or maybe i use it in wrong way?

**Comment by TurboMask** [comment]
Actually you don't need this method on Android - you get purchased items together with IAP data, when calling `getProductsInfo`. With `PRODUCT_INFO_RECEIVED` event you get JSON data with nodes `details` and `purchases`, one lists IAP data and other purchased product ID's.
