### ISSUE TITLE
Build with Amazon IAP 2.0

### ISSUE THREAD

**Issue by shalamov** [freshplanet/ANE-In-App-Purchase#55]
Hey there, I'd like to tell you about a problem which have caused me a lot of pain these days. Do you have in your near goals an idea to develop an extension for Amazon IAP 2.0, because it's really irritating to support previous one?

**Comment by TurboMask** [comment]
Amazon has its own AIR extension with IAP v2 support: https://developer.amazon.com/public/solutions/platforms/cross-platform/adobe-air
Of course there is more hassle to integrate two extensions instead of one, but at least Amazon's ANE is official and well supported.
