### ISSUE TITLE
in IOS, event PURCHASE_SUCCESSFULL not work?

### ISSUE THREAD

**Issue by qwpking** [freshplanet/ANE-In-App-Purchase#56]
i user in iOS, can purchase  but PURCHASE_SUCCESSFULL not work, Who can give me some help？？Thank you very much。

**Comment by kicholen** [comment]
Same here for ios 7, works fine on ios 8 though

Nvm it works. It turned out that I can't do some background work on ios 7, when another activity is at front.

I recommend digicrafts ANE-In-App-Purchase for IOS and pozirk AndroidInAppPurchase for Android

**Comment by kicholen** [comment]
Nvm it works. It turned out that I can't do some background work on ios 7, when another activity is at front.

I recommend  digicrafts ANE-In-App-Purchase for IOS and pozirk AndroidInAppPurchase for Android

**Comment by mr-gera** [comment]
please, see my example:
https://github.com/freshplanet/ANE-In-App-Purchase/issues/59
