### ISSUE TITLE
In ios 8.4 and ios 7.1 purchasing of item not working 

### ISSUE THREAD

**Issue by arvindy10** [freshplanet/ANE-In-App-Purchase#58]
This ane is working fine on ios 8.3 but nothing do on ios7.1  ,i am tracing when i click on purchase button
 [InAppPurchase]  in app purchase is supported 
[InAppPurchase] purchasing com.companyname.name.itemId.
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="DEBUG" level="com.companyname.name.itemId"]

But nothing happen when i purchase an item.

**Comment by mr-gera** [comment]
Please, see my example:

https://github.com/freshplanet/ANE-In-App-Purchase/issues/59
