### ISSUE TITLE
Working FLA test sample File

### ISSUE THREAD

**Issue by martingasparrow** [freshplanet/ANE-In-App-Purchase#64]
Hello people i am trying to add in app purchase features in my iOS app. i use Flash cc (Animate cc now) and fresh planet nativeExtension.while im testing trougth usb, it traces "in app purchase is supported"...but then nothing else happens... im trying for five days to make it run, and now i dont know what aim doing wrong,,, If somebody can, please post a working FLA file! Thanks a lot and excuses for my english!

**Comment by nsoud** [comment]
i need a flash example too.
Thank you
