### ISSUE TITLE
iOS: getProductsInfo crashes the app

### ISSUE THREAD

**Issue by yokoboko** [freshplanet/ANE-In-App-Purchase#67]
Hi,
under ios 9 and air sdk higher then 19 my app crash when i try to get product list:
getProductsInfo(["product1", "product2"], [])

if the array is empty it does not crash: getProductsInfo([], []);

I started a blank project to test this and this ANE doesn't work with version higher then SDK 19 for me.

Anyone having the same problem?

**Comment by RRAway** [comment]
I also get the crash, but not on every device I test. I am yet to figure out what the difference is.

**Comment by RRAway** [comment]
It's crashing when writing out JSON using JSONKit, just not all the time. JSONKit is really old and not maintained so it should probably just be replaced with Apple's NSJSONSerialization now. I've done that in the parts of the project that I used and it's no longer crashing for me.

**Comment by yokoboko** [comment]
RRAway can you upload your ANE so we can try it?

**Comment by RRAway** [comment]
Sure. If it works for you as well I'll tidy up the code and PR it.

[AirInAppPurchase.ane.zip](https://github.com/freshplanet/ANE-In-App-Purchase/files/379792/AirInAppPurchase.ane.zip)
