### ISSUE TITLE
How to use this Ane in IOS AIR using Flash CS6?

### ISSUE THREAD

**Issue by NathanFitchett** [freshplanet/ANE-In-App-Purchase#74]
Hey everyone can someone please help me understand how to go about implementing the services for my Game using Adobe AIR 22.0 for IOS. 

What exactly do I need in the XML? I add the Extension of course but not sure if I need anything else. 

Also dont know how to init the games. When I test I get an error saying cant connect to Itunes store Error:0

Here is how I am doing it:   _iap.init(IOS_ID, true);   

Pretty sure that is wrong. Can someone give me an example please!

**Comment by nsoud** [comment]
me too please .
Thank you

**Comment by twish-dm** [comment]
have some issues, but not know how fix it. Help me please
