### ISSUE TITLE
The bin folder & AirInAppPurchase.ane binary file has been deleted ?

### ISSUE THREAD

**Issue by wmtj** [freshplanet/ANE-In-App-Purchase#77]
The bin folder & AirInAppPurchase.ane binary file was missing...

**Comment by hotfix519** [comment]
https://github.com/freshplanet/ANE-In-App-Purchase/commit/559813626491e9039eb6f7c80ef572c2266e667e

You can find a working binary here.  This won't have support for iOS subscriptions, which may or may not be important to you.

If it is, you'll have to compile it yourself.

**Comment by wmtj** [comment]
@chrismarrin  Thanks ! I will try the ane binary first, and then if I need subscriptions, I will compile it. 
PS: Making the binary shown may be better for newbie  :)
