### ISSUE TITLE
Product info received handler is not getting triggered 

### ISSUE THREAD

**Issue by iOSProgrammer** [freshplanet/ANE-In-App-Purchase#8]
I m want to implement In-app-purchase in my game, i had used the latest ane from feature/googleplay-v3. But when i try to send the product info, it shows that getProductsInfo() is successfully being called but it dosent trigger the handler. Its shows the following trace

[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="PRODUCT_INFO_RECEIVED" level="{"details":{"android.test.purchased":"{\"title\":\"Sample Title\",\"price\":\"Rs. 54.27\",\"type\":\"subs\",\"description\":\"Sample description for product: android.test.purchased.\",\"productId\":\"android.test.purchased\"}"},"purchases":{}}"]

**Comment by k2xl** [comment]
Same. Ever figure this out?

**Comment by RyanBertrand** [comment]
Did anyone figure this out?

**Comment by alamboley** [comment]
Well maybe it's not related but how do you add the Android key?

**Comment by randoom** [comment]
to add the key: inAppPurchase.init(googlePlayLicenseKey, true);
Having the same problem, events not firing in feature/googleplay-v3

**Comment by iOSProgrammer** [comment]
Thanks all.... its done
